Fix an issue where a pointer was used instead of a char*
libnativehelper/JniInvocation.c:164:40: error: format specifies type 'char *' but the argument has type 'DlLibrary' (aka 'void *') [-Werror,-Wformat]
      ALOGE("Failed to dlopen %s: %s", library, DlGetError());
                              ~~       ^~~~~~~

Bug: http://b/155835175
Test: m with aosp_blueline
Change-Id: I2473574822cf819be4fe0b4db49b94b174f34696